[workspace]
members = [
    "gca",
    "gca-rt/log",
    "gca-rt/panic-log",
    "gca-rt/event",
    "gca-rt/tx",
    "gca-rt/env",
    "gca-rt/block",

    "gca-runtime",
]
exclude = [
    "examples/*"
]

