# Test

[tasks.build-example]
command = "cargo"
args = ["build", "--manifest-path", "examples/Cargo.toml", "--target", "wasm32-unknown-unknown", "--release"]

[tasks.test]
workspace = false
dependencies = ["build-example"]
command = "cargo"
args = ["test"]

## Test nocapture

[tasks.test-nocapture]
workspace = false
dependencies = ["build-example"]
command = "cargo"
env = { "RUST_LOG" = "debug" }
args = ["test", "--", "--nocapture"]

## Define clean command

[tasks.clean-example]
command = "cargo"
args = ["clean", "--manifest-path", "examples/Cargo.toml"]

[tasks.clean-gca]
command = "cargo"
args = ["clean"]

[tasks.clean]
workspace = false
dependencies = ["clean-example", "clean-gca"]

