[package]
name = "gca-measurer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parity-wasm = "0.42.2"
pwasm-utils = "0.19.0"

gca-runtime = { path = "../gca-runtime" }

